// examples/next-js/app/page.tsx
'use client';

import { TransactionDemo } from '@/components/transactions';
import { ConnectButton, ClusterSelector, AccountSwitcher } from '@/components/connector';
import { useConnector } from '@solana/connector';
import Link from 'next/link';

export default function Home() {
    const { connected } = useConnector();

    return (
        <div className="min-h-screen bg-gradient-to-b from-background to-muted/20">
            {/* Header */}
            <header className="border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 sticky top-0 z-50">
                <div className="container mx-auto px-4 h-16 flex items-center justify-between">
                    <div className="flex items-center gap-4">
                        <span className="font-semibold text-lg">ConnectorKit Demo</span>
                        <Link 
                            href="/playground" 
                            className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                        >
                            Blocks Playground →
                        </Link>
                    </div>
                    <div className="flex items-center gap-2">
                        {connected && (
                            <>
                                <ClusterSelector />
                                <AccountSwitcher />
                            </>
                        )}
                        <ConnectButton />
                    </div>
                </div>
            </header>

            {/* Main Content */}
            <main className="container mx-auto px-4 py-6">
                <div className="max-w-7xl mx-auto">
                    <div className="mb-6">
                        <h1 className="text-3xl font-bold">ConnectorKit Examples</h1>
                        <p className="text-muted-foreground mt-1">
                            Test transactions, Kit signers, chain utilities, and connection abstraction
                        </p>
                    </div>
                    <TransactionDemo />
                </div>
            </main>
        </div>
    );
}

// examples/vue/src/App.vue
<script setup lang="ts">
import { useConnectorClient, useAccount, useCluster, useWalletInfo } from './composables/useConnector'
import ConnectButton from './components/ConnectButton.vue'
import ClusterSelector from './components/ClusterSelector.vue'
import WalletInfo from './components/WalletInfo.vue'

const { connected } = useAccount()
</script>

<template>
  <div class="min-h-screen bg-gradient-to-b from-background to-secondary/20">
    <header class="border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
      <div class="container mx-auto px-4 h-16 flex items-center justify-between">
        <div class="flex items-center gap-2">
          <h1 class="text-xl font-bold">ConnectorKit</h1>
          <span class="inline-flex items-center rounded-md border px-2.5 py-0.5 text-xs font-semibold">
            Vue
          </span>
        </div>
        <div class="flex items-center gap-2">
          <ClusterSelector />
          <ConnectButton />
        </div>
      </div>
    </header>

    <main class="container mx-auto px-4 py-12 flex flex-col items-center">
      <WalletInfo />
    </main>
  </div>
</template>

<style scoped>
</style>
